config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get 'archives/index'
  resources :entries
  root to: 'entries#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/entry.rb
# frozen_string_literal: true

# `@meal_type[min: 2]`
# `@calories`
# `@proteins`
# `@carbohydrates`
# `@fats`
class Entry < ApplicationRecord
  validates :meal_type, length: { minimum: 2 }
  validates :meal_type,
            :calories,
            :proteins,
            :carbohydrates,
            :fats,
            presence: true

  before_save :title_fixer

  def day
    created_at.strftime('%b %e, %Y')
  end

  def title_fixer
    ## add a case to capitalize after [&, -, /]
    self.meal_type = meal_type.split(/ |_/).map(&:capitalize).join(' ')
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/archives_controller.rb
# frozen_string_literal: true

class ArchivesController < ApplicationController
  def index
    @archive = Entry.all.group_by(&:day)
  end
end

app/controllers/entries_controller.rb
# frozen_string_literal: true

# Controller
class EntriesController < ApplicationController
  before_action :set_entry, only: %i[show edit update destroy]

  # GET /entries or /entries.json
  def index
    date = Date.today.in_time_zone('America/Sao_Paulo')
    @entries = Entry.where(created_at: date.all_day)
  end

  # GET /entries/1 or /entries/1.json
  def show = nil

  # GET /entries/new
  def new
    @entry = Entry.new
  end

  # GET /entries/1/edit
  def edit = nil

  # POST /entries or /entries.json
  def create
    @entry = Entry.new(entry_params)
    respond_to_save(
      @entry.save,
      "#{@entry.meal_type} was successfully created."
    )
  end

  # PATCH/PUT /entries/1 or /entries/1.json
  def update
    respond_to_save(
      @entry.update(entry_params),
      "#{@entry.meal_type} was successfully updated."
    )
  end

  # DELETE /entries/1 or /entries/1.json
  def destroy
    @entry.destroy
    respond_to do |format|
      format.html do
        redirect_to entries_url,
                    notice: "#{@entry.meal_type} was successfully destroyed."
      end
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_entry
    @entry = Entry.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def entry_params
    params.require(:entry).permit(
      :meal_type,
      :calories,
      :proteins,
      :carbohydrates,
      :fats
    )
  end

  def respond_to_save(func, notice)
    respond_to do |format|
      if func
        format.html { redirect_to entry_url(@entry), notice: notice.to_s }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/archives_helper.rb
module ArchivesHelper
end

app/helpers/entries_helper.rb
module EntriesHelper
end

app/views/archives/index.html.erb
<%= content_for :subtitle do %>
  <p class="subtitle is-size-5 has-text-weight-bold has-text-black">
    Archive
  </p>
<% end %>

<div class="columns is-centered mt-2">
  <div class="column is-half">

    <% @archive.each do |day, entries| %>
      <div class="mb-6">
        <h3 class = "notification is-primary is-size-4 has-text-weight-bold mb-0 has-text-dark has-text-centered">
          Entries for <%= day %>
        </h3>

        <nav class="level is-mobile message pb-3 pt-3 m-0 is-family-monospace">
          <div class="level-item has-text-centered">
            <div>
              <p class="heading">Calories</p>
              <p class="title"><%= entries.pluck(:calories).sum %></p>
            </div>
          </div>

          <div class="level-item has-text-centered">
            <div>
              <p class="heading">Proteins</p>
              <p class="title"><%= entries.pluck(:proteins).sum %>g<g/p>
            </div>
          </div>
          
          <div class="level-item has-text-centered">
            <div>
              <p class="heading">Carbohydrates</p>
              <p class="title"><%= entries.pluck(:carbohydrates).sum %>g</p>
            </div>
          </div>

          <div class="level-item has-text-centered">
            <div>
              <p class="heading">Fats</p>
              <p class="title"><%= entries.pluck(:fats).sum %>g</p>
            </div>
          </div>
        </nav>

        <% entries.each do |entry| %>
          <%= link_to entry_path(entry) do %>
            <div class="card">
              <div class="card-content">
                <strong class = "card-title"><%= entry.meal_type %></strong><br>
                <div class="card-subtitle">
                  <%= entry.calories %> calories,
                  <%= entry.proteins %>g protein,
                  <%= entry.carbohydrates %>g carbs,
                  <%= entry.fats %>g fats
                </div>
              </div>
            </div>
          <% end %>
        <% end %>

      </div>
    <% end %>

  </div>

</div>

app/views/entries/_display.html.erb
<div class="column is-one-third">
  <nav class="panel is-link">
    <p class="panel-heading">
      <%= @entry.meal_type %>
    </p>
    <div class="panel-block">
      Calories: <%= @entry.calories %>
    </div>
    <div class="panel-block">
      Proteins: <%= @entry.proteins %>
    </div>
    <div class="panel-block">
      Carbs: <%= @entry.carbohydrates %>
    </div>
    <div class="panel-block">
      Fats: <%= @entry.fats %>
    </div>
  </nav>

  <div class="container is-pulled-left">
    <%= link_to 'back', root_path, class: "is-family-monospace button is-dark is-outlined"%>
  </div>
  <div class="container is-pulled-right">
    <%= button_to 'delete', entry_path(@entry), method: :delete, data: {
        confirm: "Are you sure you want to remove #{@entry.meal_type}"
      }, class: "is-family-monospace button is-danger is-outlined"%>
  </div>
  <div class="container mr-1 is-pulled-right">
    <%= link_to 'edit', edit_entry_path(@entry), class: "is-family-monospace button is-link is-outlined"%>
  </div>
</div>

app/views/entries/_entry.html.erb
<% @entries.each_with_index do |entry, index| %>
  <% if index % 3 == 0 %>
    <div class="columns is-desktop is-centered">
  <% end %>
  <div class="column is-4">
    <%= link_to entry do %>
      <div class="card mb-3">
        <nav class = "panel is-link">
          <header class = "panel-heading">
            <%= entry.meal_type %>
          </header>

          <a class = "panel-block">
            <b> <%= entry.calories %></b> &nbsp;
            calories
          </a>
          <a class = "panel-block">
            <b> <%= entry.proteins %></b> &nbsp;
            grams of proteins
          </a>
          <p class = "panel-block">
            <b><%= entry.carbohydrates %></b> &nbsp;
             grams of carbs
          </p>
          <a class = "panel-block">
            <b><%= entry.fats %></b> &nbsp;
            grams of fat
          </a>
          <a class = "panel-block">
            <h1 class = "has-text-weight-light">
              <%= time_ago_in_words(entry.created_at).capitalize %> ago.
            </h1>
          </a>

          <div class = "panel">
            <div class="level-right">

            <%= button_to 'Delete', entry, method: :delete,
              form: { data: { turbo_confirm: 'Are you sure?' } },
              :class => 'button is-danger is-outlined m-1' %>
            </div>
          </div>
        </nav>
      </div>
    <% end %>
  </div>
  <% if index % 3 == 2 || @entries.size == index + 1 %>
    </div>
  <% end %>
<% end %>

app/views/entries/_form.html.erb
<%= form_with(model: entry) do |form| %>
  <% if entry.errors.any? %>
    <div class="message is-danger is-light">
      <div class="message-header">
        <h2><%= pluralize(entry.errors.count, "error") %> prohibited this entry from being saved:</h2>
      </div>
      <ul>
        <% entry.errors.each do |error| %>
          <li class = "m-1" ><%= error.full_message %>.</li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class = "field">
    <%= form.label :meal_type, style: "display: block", class: "label" %>
    <div class = "control">
      <%= form.text_field :meal_type, class: "input" %>
      </div>
  </div>

  <div class = "field">
    <%= form.label :calories, style: "display: block", class: "label" %>
    <div class = "control">
      <%= form.number_field :calories, class: "input" %>
      </div>
  </div>

  <div class = "field">
    <%= form.label :proteins, style: "display: block", class: "label" %>
    <div class = "control">
      <%= form.number_field :proteins, class: "input" %>
      </div>
  </div>

  <div class = "field">
    <%= form.label :carbohydrates, style: "display: block", class: "label" %>
    <div class = "control">
      <%= form.number_field :carbohydrates, class: "input" %>
      </div>
  </div>

  <div class = "field">
    <%= form.label :fats, style: "display: block", class: "label" %>
    <div class = "control">
      <%= form.number_field :fats, class: "input" %>
      </div>
  </div>

  <div class="container is-pulled-left">
      <%= form.submit submit_action, class: "is-family-monospace button is-primary" %>
  </div>
  <div class="container is-pulled-right">
    <%= link_to "Cancel", entries_path, class: "is-family-monospace button is-light" %>
  </div>
<% end %>

app/views/entries/edit.html.erb
<% content_for :subtitle do %>
  <p class = "subtitle is-size-5 has-text-weight-bold">Editing 
    <span class = "has-text-warning" ><%= @entry.meal_type %></span>
  </p>
<% end %>

<div class="columns is-centered mt-1">
  <%= render "form", entry: @entry, submit_action: 'Update' %>
</div>

app/views/entries/index.html.erb
<%= content_for :subtitle do %>
  <p class="subtitle is-size-5 has-text-weight-bold has-text-black">
    <%= Date.today.strftime("%e %b, %Y") %>
  </p>
<% end %>

<%= render "entry" %>

<div class="columns is-centered mb-6">
  <%= link_to 'View All Entries', archives_index_path, class: 'button is-link is-outlined' %>
</div>

app/views/entries/new.html.erb
<% content_for :subtitle do %>
  <p class = "subtitle is-size-5 has-text-weight-bold">Creating 
    <span class = "has-text-success" >New Meal</span>
  </p>
<% end %>

<div class="columns is-centered mt-1">
  <%= render "form", entry: @entry, submit_action: 'Create' %>
</div>

app/views/entries/show.html.erb
<% content_for :title do %>
  <p class = "title has-text-light" >
    <%= @entry.meal_type %>
  </p>
<% end %>

<% content_for :subtitle do %>
  <p class = "subtitle is-size-5 has-text-weight-bold has-text-black" >
    Food App
  </p>
<% end %>

<div class="columns mt-2 is-centered">
  <%= render "display", entry: @entry %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Food App</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.9.4/css/bulma.min.css">
    <%= javascript_include_tag "application" %>
    <%= javascript_importmap_tags %>
    
  </head>

  <body>
    <%= render "shared/header" %>
    
    <% if notice.present? %>
      <div class="notification is-link is-light">
        <%= notice %>
      </div>
    <% end %>

    <% if alert.present? %>
      <div class="notification is-danger is-light">
        <%= alert %>
      </div>
    <% end %>

    <div class="container">
      <%= yield %>
    </div>
  </body>
  <script defer src="https://use.fontawesome.com/releases/v5.3.1/js/all.js"></script>
</html>

app/views/shared/_header.html.erb
<section class="block hero is-link">
  <!-- Hero head: will stick at the top -->
  <div class="hero-head">
    <header class="navbar is-link">
      <div class="navbar-brand">
        <%= link_to root_path, class: "navbar-item" do %>
        <?xml version="1.0" encoding="utf-8"?>
          <span class = " has-text-black has-text-weight-bold is-size-4 ml-2 mr-2 is-black">Food App</span>
          <!-- Uploaded to: SVG Repo, www.svgrepo.com, Generator: SVG Repo Mixer Tools -->
          <svg width="00px" height="800px" viewBox="0 0 1024 1024" class="icon"  version="1.1" xmlns="http://www.w3.org/2000/svg"><path d="M579.8 289.5l-42-169.2L389 143.7c-9.8 1.5-18.9-5.1-20.5-14.9l-2.2-14c-1.5-9.8 5.1-18.9 14.9-20.5L556 66.9c10.8-1.7 21.2 5.2 23.8 15.8l48.4 194.8c2.4 9.6-3.5 19.3-13.1 21.7l-13.7 3.4c-9.5 2.4-19.3-3.5-21.6-13.1z" fill="#656666" /><path d="M240.7 749.9m-176.5 0a176.5 176.5 0 1 0 353 0 176.5 176.5 0 1 0-353 0Z" fill="#FF9D00" /><path d="M164.2 601.3c28.6 14.4 59.3 20.3 89.1 18.7-4.1-60.1-38.9-116.6-96.6-145.7-28.6-14.4-59.3-20.3-89.1-18.7 4.1 60.2 38.9 116.6 96.6 145.7z" fill="#02BA4D" /><path d="M860.4 926.9H542.6c-18 0-32.9-12.3-34.5-28.3l-60-601.7c-0.7-7.4 5.8-13.9 14.2-13.9h479.2c8.4 0 14.9 6.5 14.1 13.9l-63.4 604c-1.5 14.7-15.3 26-31.8 26z" fill="#00AAFF" /></svg>
        <% end %>
        <span class="navbar-burger burger" role = "button" data-target="navbarMenuHeroC">
          <span aria-hidden="true"></span>
          <span aria-hidden="true"></span>
          <span aria-hidden="true"></span>
        </span>
      </div>
      <div id = "navbarMenuHeroC" class="navbar-menu">
        <div class="navbar-start">
          <%= link_to "Entries", entries_path, class: "navbar-item" %>
          <%= link_to "Create Entry", new_entry_path, class: "navbar-item" %>
          <%# TODO: REMOVE THIS ACTIVE RECORD OPERATIONS BELOW %>
          <%= link_to "Edit Entry", edit_entry_path(Entry.last), class: "navbar-item" %>
          <%= link_to "Show Entry", entry_path(Entry.last), class: "navbar-item" %>
        </div>
      </div>
    <div class="navbar-end">
      <div class="navbar-item">
        <div class="buttons">
          <a class="button is-primary">
            <strong>Sign up</strong>
          </a>
          <a class="button is-light">
            Log in
          </a>
        </div>
      </div>
    </div>
    </header>
  </div>

  <!-- Hero content: will be in the middle -->
  <div class="hero-body">
    <div class="container has-text-centered">
      <% if content_for :title %>
        <%= yield :title %>
      <% else %>
        <p class = "title" >Food App</p>
      <% end %>
      <% if content_for :subtitle %>
        <%= yield :subtitle %>
      <% else %>
        <p class="subtitle"></p>
      <% end %>
    </div>
  </div>
</section>